"""Event types for Valkyrie's message bus.

Two message types flow through the system:
- InboundMessage: arrives from a channel (Moltbook post, Telegram DM, etc.)
- OutboundMessage: generated by weave.py, routed back to the originating channel
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class InboundMessage:
    """A message received from any channel."""

    channel: str          # "moltbook", "telegram", "discord", etc.
    sender_id: str        # Who sent it (platform-specific ID)
    chat_id: str          # Conversation/thread identifier
    content: str          # The actual text
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    media: list[str] = field(default_factory=list)       # File paths or URLs
    metadata: dict[str, Any] = field(default_factory=dict)  # Channel-specific extras

    @property
    def session_key(self) -> str:
        """Unique key for session tracking: '{channel}:{chat_id}'."""
        return f"{self.channel}:{self.chat_id}"


@dataclass
class OutboundMessage:
    """A message to send through a channel."""

    channel: str
    chat_id: str
    content: str
    reply_to: str | None = None
    media: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)